replicaCount: 1

image:
    repository: 149536461874.dkr.ecr.eu-west-1.amazonaws.com/tech4dev-microservices/go-service
    tag: latest
    pullPolicy: IfNotPresent

service:
    type: ClusterIP
    port: 8080
