replicaCount: 1

image:
    repository: 149536461874.dkr.ecr.eu-west-1.amazonaws.com/tech4dev-microservices/python-service
    tag: latest
    pullPolicy: IfNotPresent

service:
    type: ClusterIP
    port: 8000

env:
    GO_SERVICE_HOST: go-service
    GO_SERVICE_PORT: "8080"
