@Library('shared-library') _

pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = credentials('AWS_REGION')
        ECR_REGISTRY = credentials('ECR_REGISTRY')
    }

    stages {
        stage('Init') {
            steps {
                script {
                    
                    env.IMAGE_TAG = generateImageTag()
                }
            }
        }

        stage('Login to ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-keys'
                ]]) {
                    sh '''
                        aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
                          docker login --username AWS --password-stdin $ECR_REGISTRY
                    '''
                }
            }
        }

        stage('Build & Push Go Service') {
            when {
                changeset "**/microservices/go-service/**"
            }
            steps {
                dir('microservices/go-service') {
                    script {
                        def image = docker.build("${ECR_REGISTRY}/go-service:${env.IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }

        stage('Build & Push Python Service') {
            when {
                changeset "**/microservices/python-service/**"
            }
            steps {
                dir('microservices/python-service') {
                    script {
                        def image = docker.build("${ECR_REGISTRY}/python-service:${env.IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }

        stage('Build & Push Rail Service') {
            when {
                changeset "**/microservices/rail-service/**"
            }
            steps {
                dir('microservices/rail-service') {
                    script {
                        def image = docker.build("${ECR_REGISTRY}/rail-service:${env.IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }

        stage('Terraform Apply') {
            when {
                changeset "terraform/**"
            }
            steps {
                dir('terraform') {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-keys'
                    ]]) {
                        sh '''
                            terraform init
                            terraform validate
                            terraform plan -out=tfplan
                            terraform apply -auto-approve tfplan
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
