apiVersion: apps/v1
kind: Deployment
metadata:
    name: { { include "app.fullname" . } }
spec:
    replicas: 1
    selector:
        matchLabels:
            app: { { include "app.name" . } }
    template:
        metadata:
            labels:
                app: { { include "app.name" . } }
        spec:
            containers:
                - name: { { include "app.name" . } }
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  ports:
                      - containerPort: 8080
                  env:
                      - name: GO_SERVICE_HOST
                        value: "go-service"
                      - name: GO_SERVICE_PORT
                        value: "8080"
