pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = credentials('AWS_REGION')
        ECR_REGISTRY = credentials('ECR_REGISTRY')
    }

    stages {
        stage('Generate Version') {
            steps {
                script {
                    // Get the current date in the format yyyy.mm.dd
                    def date = sh(script: "date +'%Y.%m.%d'", returnStdout: true).trim()
                    // Use Jenkins build number as the build ID
                    def buildId = env.BUILD_NUMBER
                    // Generate the image tag
                    env.IMAGE_TAG = "${date}.${buildId}"
                    echo "Image tag: ${env.IMAGE_TAG}"
                }
            }
        }

        stage('Login to ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-keys'
                ]]) {
                    sh '''
                        aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
                          docker login --username AWS --password-stdin $ECR_REGISTRY
                    '''
                }
            }
        }

        stage('Build & Push Go Service') {
            steps {
                dir('microservices/go-service') {
                    script {
                        def image = docker.build("${ECR_REGISTRY}/go-service:${IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }

        stage('Build & Push Python Service') {
            steps {
                dir('microservices/python-service') {
                    script {
                        def image = docker.build("${ECR_REGISTRY}/python-service:${IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }

        stage('Build & Push Rail Service') {
            steps {
                dir('microservices/rail-service') {
                    script {
                        def image = docker.build("${ECR_REGISTRY}/rails-service:${IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
